max_threads: 8
singlem_metapackage: 
genomes:
  genome: 
taxa_of_interest: ""
max_coassembly_size: 
assemble_unmapped: false
sra: false
prodigal_meta: false
single_assembly: false
no_genomes: false
new_genomes: false
exclude_coassemblies: 
appraise_sequence_identity: 1
min_coassembly_coverage: 1
num_coassembly_samples: 1
max_coassembly_samples: 1
max_recovery_samples: 1
unmapping_min_appraised: 1
unmapping_max_identity: 1
unmapping_max_alignment: 1
aviary_speed: "fast"
run_aviary: false
aviary_gtdbtk: ""
aviary_checkm2: ""
aviary_memory: 1
aviary_threads: 1
test: false
mock_sra: false
aviary_dryrun: false
conda_prefix: false
